# Generated by Django 3.2.13 on 2022-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220624_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog_post/default.jpg', upload_to='blog_post/'),
        ),
    ]
